[project]
name = "gentext-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zhtdbb1", email = "arthurzhu0523@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "en-core-web-lg",
    "fastapi[standard]>=0.142.2",
    "spacy>=3.8,<3.9",
]

[project.scripts]
gentext-app = "gentext_app:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
en-core-web-lg = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl" }
